### ISSUE TITLE
unsqueeze+conv2d error

### ISSUE THREAD

**Issue by mhmd97z** [Verified-Intelligence/alpha-beta-CROWN#34]
Hi, I am trying to simulate the conv1d operation using unsqueeze+conv2d (as conv1d is not already supported), but I get this error that I cannot fix. When I remove the convolutional layer, I do not get the error, so the error should have something to do with conv2d. I'd appreciate your help.

The error:
```
Model prediction is: tensor([0.17936328], device='cuda:0')
initial forward+backward bounds (first 10): tensor([-0.18187992], device='cuda:0')
Traceback (most recent call last):
  File "abcrown.py", line 666, in <module>
    main()
  File "abcrown.py", line 589, in main
    refined_betas=refined_betas, attack_images=all_adv_candidates, attack_margins=attack_margins)
  File "abcrown.py", line 410, in complete_verifier
    rhs=rhs, timeout=timeout, attack_images=this_spec_attack_images)
  File "abcrown.py", line 200, in bab
    rhs=rhs, timeout=timeout, branching_method=arguments.Config["bab"]["branching"]["method"])
  File "/home/mzi/sys-rl-verif/alpha-beta-CROWN/complete_verifier/batch_branch_and_bound_input_split.py", line 297, in input_bab_parallel
    stop_func=stop_func,
  File "/home/mzi/sys-rl-verif/alpha-beta-CROWN/complete_verifier/batch_branch_and_bound_input_split.py", line 71, in batch_verification_input_split
    stop_criterion_func=stop_func(thresholds),
  File "/home/mzi/sys-rl-verif/alpha-beta-CROWN/complete_verifier/beta_CROWN_solver.py", line 1518, in get_lower_bound_naive
    bound_upper=False, return_A=True, needed_A_dict=needed_A_dict)
  File "/home/mzi/sys-rl-verif/alpha-beta-CROWN/complete_verifier/auto_LiRPA/bound_general.py", line 1328, in compute_bounds
    unstable_idx=alpha_idx, update_mask=update_mask)
  File "/home/mzi/sys-rl-verif/alpha-beta-CROWN/complete_verifier/auto_LiRPA/backward_bound.py", line 221, in backward_general
    lb = lb.view(batch_size, *output_shape) if bound_lower else None
RuntimeError: shape '[8192, 1]' is invalid for input of size 67108864
```

The model:
```
class MyModel(nn.ModuleList):
        def __init__(self, device=torch.device("cpu")):
            super(MyModel, self).__init__()        
            self.to(device)

            self.af = nn.ReLU()
            self.lin1 = nn.Linear(19, 32)
            self.lin2 = nn.Linear(32, 32)
            self.lin3 = nn.Linear(32, 15)

            self.conv2d = nn.Conv2d(
                in_channels=1, out_channels=1, kernel_size=(1, 15)
            )

        def forward(self, obs):
            lin1 = self.af(self.lin1(obs))
            lin2 = self.af(self.lin2(lin1))
            lin3 = self.lin3(lin2).unsqueeze(0).unsqueeze(0)
            conved = self.conv2d(lin3)

            return conved[0][0]
```

YAML file:
```
general:
  enable_incomplete_verification: False
  loss_reduction_func: max
  conv_mode: matrix
model:
  name: cmars
  input_shape: [1, 19]
specification:
  vnnlib_path: /home/mzi/sys-rl-verif/verif-slicing/cmars/vnnlib/large_1/N8/h32/basic-a1.vnnlib
attack:
  pgd_order: skip
solver:
  bound_prop_method: forward+backward
bab:
  method: sb
  input_split:
    enable: True
    adv_check: .inf
VNNLib property is as that in my previous question.
```

basic.vnnlib
```
(declare-const X_0 Real)
(declare-const X_1 Real)
(declare-const X_2 Real)
(declare-const X_3 Real)
(declare-const X_4 Real)
(declare-const X_5 Real)
(declare-const X_6 Real)
(declare-const X_7 Real)
(declare-const X_8 Real)
(declare-const X_9 Real)
(declare-const X_10 Real)
(declare-const X_11 Real)
(declare-const X_12 Real)
(declare-const X_13 Real)
(declare-const X_14 Real)
(declare-const X_15 Real)
(declare-const X_16 Real)
(declare-const X_17 Real)
(declare-const X_18 Real)

(declare-const Y_0 Real)

(assert (or 
	(and (<= X_0 0.11281310021877289) (>= X_0 0.08347102999687195) (<= X_1 -0.04856841638684273) (>= X_1 -0.07791049033403397) (<= X_2 -0.004555195104330778) (>= X_2 -0.033897269517183304) (<= X_3 0.06879998743534088) (>= X_3 0.03945791721343994) (<= X_4 0.1568262130022049) (>= X_4 0.12748414278030396) (<= X_5 0.2448524385690689) (>= X_5 0.21551036834716797) (<= X_6 0.2595234811306) (>= X_6 0.23018139600753784) (<= X_7 0.33287864923477173) (>= X_7 0.303536593914032) (<= X_8 0.42090487480163574) (>= X_8 0.391562819480896) (<= X_9 0.42090487480163574) (>= X_9 0.391562819480896) (<= X_10 0.391562819480896) (>= X_10 0.36222073435783386) (<= X_11 0.47958904504776) (>= X_11 0.4502469599246979) (<= X_12 0.6262993812561035) (>= X_12 0.5969573259353638) (<= X_13 0.6996545791625977) (>= X_13 0.6703125238418579) (<= X_14 0.7143256068229675) (>= X_14 0.6849835515022278) (<= X_15 0.6262993812561035) (>= X_15 0.5969573259353638) (<= X_16 0.5529442429542542) (>= X_16 0.5236021280288696) (<= X_17 0.4502469599246979) (>= X_17 0.42090487480163574) (<= X_18 0.4942600727081299) (>= X_18 0.46491798758506775) (>= Y_0 0))
))
```

**Comment by huanzhang12** [comment]
@mhmd97z Thank you for reporting this - the good news is that Conv1d will be added in our next release in October. So you will be able to directly use it soon. The next release is planned to be in October; stay tuned!
