### ISSUE TITLE
AssertionError Due to Certain Data

### ISSUE THREAD

**Issue by r11942152** [Verified-Intelligence/alpha-beta-CROWN#36]
Dear alpha-beta-CROWN Team,

I would like to extend my gratitude for your excellent work.

Your sample code works perfectly when we run it.

However, I'm writing to report an issue that I encountered 
while attempting to run your sample code with a custom model using the following command:
```
python abcrown.py --config exp_configs/mnist_S.yaml
```

To provide some context, I added a custom model definition in **model_defs.py**, which looks as follows:
```
def conv_S():
    model = nn.Sequential(
        nn.Conv2d(1, 16, 4, stride=2, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2),
        nn.Conv2d(16, 32, 4, stride=2, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2),
        Flatten(),
        nn.Linear(32, 24),
        nn.ReLU(),
        nn.Linear(24, 10)
    )
    return model
```
At this point, the code executes perfectly in idx 0 to 12 but has a result in  idx 13, 
it encounters the following issue:
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% idx: 13, vnnlib ID: 13 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Attack parameters: initialization=uniform, steps=100, restarts=100, alpha=0.025000005960464478, initialization=uniform, GAMA=False
Model output of first 5 examples:
 tensor([[ 9.34262276, -7.84992790,  1.48994040, -5.32939434, -1.97707677,
          0.06667299,  0.49797791, -3.03078222,  2.04741216, -0.75792819]],
       device='cuda:0')
Adv example prediction (first 2 examples and 2 restarts):
 tensor([[[ 6.48601294, -7.30414724,  0.62207073, -3.60429788, -2.02184796,
          -0.06410425, -1.29587710, -2.43488121,  4.11566591,  1.92593360],
         [ 6.48601294, -7.30414724,  0.62207073, -3.60429788, -2.02184796,
          -0.06410425, -1.29587710, -2.43488121,  4.11566591,  1.92593360]]],
       device='cuda:0')
PGD attack margin (first 2 examles and 10 specs):
 tensor([[[13.79016018,  5.86394215, 10.09031105,  8.50786114,  6.55011702,
           7.78188992,  8.92089462,  2.37034702,  4.56007957]]],
       device='cuda:0')
number of violation:  0
Attack finished in 0.3795 seconds.
PGD attack failed
/home/user/anaconda3/envs/alpha-beta-crown/lib/python3.7/site-packages/torch/nn/functional.py:749: UserWarning: Note that order of the arguments: ceil_mode and return_indices will changeto match the args list in nn.MaxPool2d in a future release.
  warnings.warn("Note that order of the arguments: ceil_mode and return_indices will change"
Model prediction is: tensor([[ 9.34262276, -7.84992790,  1.48994040, -5.32939434, -1.97707677,
          0.06667299,  0.49797791, -3.03078222,  2.04741216, -0.75792819]],
       device='cuda:0')
layer /10 using sparse-features alpha with shape [1178]; unstable size 1178; total size 3136 (torch.Size([1, 16, 14, 14]))
layer /10 start_node /input.8 using sparse-spec alpha with unstable size 166 total_size 288 output_shape (32, 3, 3)
layer /10 start_node /input.12 using sparse-spec alpha with unstable size 21 total_size 24 output_shape torch.Size([24])
layer /10 start_node /25 using full alpha with unstable size None total_size 9 output_shape 9
Traceback (most recent call last):
  File "abcrown.py", line 647, in <module>
    main()
  File "abcrown.py", line 535, in main
    incomplete_verifier(model_ori, x, data_ub=data_max, data_lb=data_min, vnnlib=vnnlib)
  File "abcrown.py", line 69, in incomplete_verifier
    domain, x, data_lb, data_ub, vnnlib, stop_criterion_func=stop_criterion_min(arguments.Config["bab"]["decision_thresh"]))
  File "/home/user/alpha-beta-CROWN/complete_verifier/beta_CROWN_solver.py", line 1069, in build_the_model
    (self.x,), share_slopes=share_slopes, c=self.c, bound_upper=False)
  File "/home/user/alpha-beta-CROWN/complete_verifier/auto_LiRPA/optimized_bounds.py", line 1050, in init_slope
    final_node_name=final_node_name)
  File "/home/user/alpha-beta-CROWN/complete_verifier/auto_LiRPA/backward_bound.py", line 760, in get_alpha_crown_start_nodes
    assert not sparse_intermediate_bounds or use_sparse_conv is False  # Double check our assumption holds. If this fails, then we created wrong shapes for alpha.
AssertionError
```
It would be greatly appreciated if you could provide guidance or support to help me overcome this problem.

For your convenience, I have prepared our materials, including **mnist_S.yaml**, **ConvS-custom.pth** and **model_defs.py**, with
```
wget -O materials.rar https://www.dropbox.com/scl/fi/pnn7ob5focdhr6r3kr843/materials.rar?rlkey=9vp37h1gkxrhf8t2gf8fthqsg&dl=1
unrar x marerials.rar
```
Thank you in advance for your assistance.

**System configuration:**
 - OS:  Ubuntu 18.04.6 LTS
 - Python version: Python 3.7.13
 - Pytorch Version: PyTorch 1.11.0
 - Hardware: NVIDIA GeForce GTX 1080 Ti
 - Have you tried to reproduce the problem in a cleanly created conda/virtualenv environment using official installation instructions and the latest code on the main branch?: Yes

**Comment by shizhouxing** [comment]
@r11942152 Can you try adding `--no_sparse_interm`?

**Comment by r11942152** [comment]
@shizhouxing do you mean executing
```
python abcrown.py --config exp_configs/mnist_S.yaml --no_sparse_alpha
```
It will show the same error message.

**Comment by shizhouxing** [comment]
@r11942152 Sorry I find this option only exists in our internal development version. The issue mentioned here has already been fixed in the internal development version which will be released soon.
