### ISSUE TITLE
GCP-CROWN‘s SDP example error

### ISSUE THREAD

**Issue by qj1204** [Verified-Intelligence/alpha-beta-CROWN#51]
**Describe the bug**
Hi, when I reproduced the results for SDP models with GCP-CROWN, an error occurred.

**To Reproduce**
run 'python abcrown.py --config exp_configs/GCP-CROWN/mnist_cnn_a_adv.yaml'

Traceback (most recent call last):
  File "/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/abcrown.py", line 609, in <module>
    abcrown.main()
  File "/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/abcrown.py", line 588, in main
    verified_status = self.complete_verifier(
  File "/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/abcrown.py", line 399, in complete_verifier
    l, nodes, ret = self.bab(
  File "/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/abcrown.py", line 242, in bab
    result = general_bab(
  File "/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/bab.py", line 269, in general_bab
    net.set_cuts(model_incomplete.A_saved, x, ret['lower_bounds'], ret['upper_bounds'])
  File "/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/cuts/cut_verification.py", line 269, in set_cuts
    cuts = add_input_cuts(self, A, number_cuts=number_cuts, device=self.net.device)
  File "/home/ictt/miniconda3/envs/alpha-beta-crown2/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/cuts/implied_cuts.py", line 237, in add_input_cuts
    assert last_A.matmul(center) - last_A.abs().matmul(diff) + last_b < 0
AssertionError
mip solver model built in 0.6189 seconds.
lower bounds for all target labels: [1.9055490493774414, 0.5247936248779297, -2.302560329437256, -1.420586109161377, -0.5922765731811523, -0.33838844299316406, -1.5372157096862793, 1.1211633682250977, 0.47852492332458496]
Starting MIP solver for these labels: [2, 3, 4, 5, 6]
start creating model mps for candidates: ['lay/16_2', 'lay/16_3', 'lay/16_4', 'lay/16_5', 'lay/16_6']
parallel save mip model to /home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/cuts/CPLEX_cuts/cplexmip_lay-16_starttime=1708308422_idx=1_spec=2_30843038.mps
parallel save mip model to /home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/cuts/CPLEX_cuts/cplexmip_lay-16_starttime=1708308422_idx=1_spec=3_30843038.mps
parallel save mip model to /home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/cuts/CPLEX_cuts/cplexmip_lay-16_starttime=1708308422_idx=1_spec=4_30843038.mps
parallel save mip model to /home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/cuts/CPLEX_cuts/cplexmip_lay-16_starttime=1708308422_idx=1_spec=5_30843038.mps
parallel save mip model to /home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/cuts/CPLEX_cuts/cplexmip_lay-16_starttime=1708308422_idx=1_spec=6_30843038.mps
parallel mps save finish
/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/lp_mip_solver.py:1146: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/cuts/CPLEX_cuts/cplexmip_lay-16_starttime=1708308422_idx=1_spec=2_30843038.log' mode='w' encoding='ANSI_X3.4-1968'>
  proc, logfile = run_get_cuts_subprocess(model_filename_stamped)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Process Process-2:
Traceback (most recent call last):
  File "/home/ictt/miniconda3/envs/alpha-beta-crown2/lib/python3.9/multiprocessing/managers.py", line 802, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ictt/miniconda3/envs/alpha-beta-crown2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ictt/miniconda3/envs/alpha-beta-crown2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ictt/miniconda3/envs/alpha-beta-crown2/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/lp_mip_solver.py", line 1042, in construct_mip_with_model
    build_the_model_mip(model, labels_to_verify=None, save_mps=save_mps, process_dict=process_dict, x=x, intermediate_bounds=intermediate_bounds)
  File "/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/lp_mip_solver.py", line 1152, in build_the_model_mip
    raise e
  File "/home/ictt/Documents/qj/VNN/alpha-beta-CROWN/complete_verifier/lp_mip_solver.py", line 1147, in build_the_model_mip
    processes[pidx] = {'pid': proc.pid, '_logfile': logfile, '_fname_stamped': model_filename_stamped, 'c': model_c_row}
  File "<string>", line 2, in __setitem__
  File "/home/ictt/miniconda3/envs/alpha-beta-crown2/lib/python3.9/multiprocessing/managers.py", line 806, in _callmethod
    self._connect()
  File "/home/ictt/miniconda3/envs/alpha-beta-crown2/lib/python3.9/multiprocessing/managers.py", line 793, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/home/ictt/miniconda3/envs/alpha-beta-crown2/lib/python3.9/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/home/ictt/miniconda3/envs/alpha-beta-crown2/lib/python3.9/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
/home/ictt/miniconda3/envs/alpha-beta-crown2/lib/python3.9/subprocess.py:1052: ResourceWarning: subprocess 4172529 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback

**System configuration:**
NVIDIA TITAN RTX   24G.
environment_pyt111.yaml

How to solve the problem?

**Comment by yiyuanchun** [comment]
I encountered the same error as you. If you have resolved this issue, I kindly ask you to share the solution with me. Thank you very much!
